AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Resources:
  ItemsApiFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: items-api-local
      Runtime: nodejs24.x
      Handler: dist/index.handler
      CodeUri: .
      MemorySize: 256
      Timeout: 10
      Environment:
        Variables:
          ENVIRONMENT: local
          TABLE_NAME: !Ref ItemsTable
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ItemsTable
      Events:
        ApiEvents:
          Type: HttpApi
          Properties:
            # This catches BOTH /items and /items/123 natively
            Path: /items/{proxy+}
            Method: ANY
            PayloadFormatVersion: "2.0" # Explicitly set for Node.js handling

  ItemsTable:
    Type: AWS::Serverless::SimpleTable
    Properties:
      TableName: items-api-local
      PrimaryKey:
        Name: id
        Type: String