AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31

Globals:
  Function:
    Runtime: nodejs24.x
    Handler: index.handler
    Environment:
      Variables:
        TABLE_NAME: !Ref ItemsTable

Resources:
  ItemsApi:
    Type: AWS::Serverless::HttpApi

  ItemsFunction:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: dist/
      Events:
        ApiEvent:
          Type: HttpApi
          Properties:
            ApiId: !Ref ItemsApi
            Path: /{proxy+}
            Method: ANY
        HealthCheck:
          Type: HttpApi
          Properties:
            ApiId: !Ref ItemsApi
            Path: /
            Method: GET
      Policies:
        - DynamoDBCrudPolicy:
            TableName: !Ref ItemsTable

  ItemsTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: items-api-dev
      BillingMode: PAY_PER_REQUEST
      AttributeDefinitions:
        - AttributeName: id
          AttributeType: S
      KeySchema:
        - AttributeName: id
          KeyType: HASH

Outputs:
  ApiUrl:
    Value: !Sub "https://${ItemsApi}.execute-api.${AWS::Region}.amazonaws.com"
